apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: voting-app
  name: postgres
  labels: 
    app: postgres
spec:
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      volumes:
        - name: postgres-storage
          persistentVolumeClaim:
            claimName: postgres-pvc
      containers:
      - name: postgres
        image: postgres
        resources:
          limits:
            memory: "128Mi"
            cpu: "300m"
          requests:
            memory: "64Mi"
            cpu: "200m"
        ports:
        - containerPort: 5432
        envFrom:
        - secretRef:
            name: voting-app-secrets
        volumeMounts:
          - mountPath: /var/lib/postgresql/data
            name: postgres-storage
