apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: voting-app
  name: postgres-pvc
  labels:
    app: postgres
spec:
  storageClassName: managed-csi
  accessModes: 
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  # selector:
  #   matchLabels:
  #     app: postgres
