apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: voting-app
  name: result-deployment
  labels:
    app: result
spec:
  selector:
    matchLabels:
      app: result
  template:
    metadata:
      labels:
        app: result
    spec:
      containers:
      - name: result
        image: votingappaks-f3e8d4b2gwhcaua7.azurecr.io/result:v1
        resources:
          limits:
            memory: "64Mi"
            cpu: "100m"
          requests:
            memory: "32Mi"
            cpu: "50m"