apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: voting-app
  name: worker-deployment
  labels:
    app: worker
spec:
  selector:
    matchLabels:
      app: worker
  template:
    metadata:
      labels:
        app: worker
    spec:
      containers:
      - name: worker
        image: votingappaks-f3e8d4b2gwhcaua7.azurecr.io/worker:v1
        resources:
          limits:
            memory: "64Mi"
            cpu: "100m"
          requests:
            memory: "32Mi"
            cpu: "50m"